/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vITs;

/**
 *
 * @author Matus
 */
public class Meny extends javax.swing.JFrame {

    /**
     * Creates new form Meny
     */
    public Meny() {
        initComponents();
        
        this.setTitle("vITs Utbildning");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpMeny = new javax.swing.JTabbedPane();
        pStartsida = new javax.swing.JPanel();
        lblVitslogga = new javax.swing.JLabel();
        pLogin = new javax.swing.JPanel();
        lblLosen = new javax.swing.JLabel();
        lblAnvnamn = new javax.swing.JLabel();
        tfAnvnamn = new javax.swing.JTextField();
        tfLosen = new javax.swing.JTextField();
        btnLoggain = new javax.swing.JButton();
        pReseforskott = new javax.swing.JPanel();
        pReseutlägg = new javax.swing.JPanel();
        pRapporter = new javax.swing.JPanel();
        pAdmin = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        tpMeny.setBackground(new java.awt.Color(255, 255, 255));

        pStartsida.setBackground(new java.awt.Color(255, 255, 255));

        lblVitslogga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vITs/logga.gif"))); // NOI18N

        pLogin.setBackground(new java.awt.Color(255, 255, 255));

        lblLosen.setText("Lösenord");

        lblAnvnamn.setText("Användarnamn");

        btnLoggain.setText("Logga in");

        javax.swing.GroupLayout pLoginLayout = new javax.swing.GroupLayout(pLogin);
        pLogin.setLayout(pLoginLayout);
        pLoginLayout.setHorizontalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLoggain, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pLoginLayout.createSequentialGroup()
                        .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAnvnamn)
                            .addComponent(lblLosen))
                        .addGap(18, 18, 18)
                        .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfAnvnamn, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(tfLosen)))))
        );
        pLoginLayout.setVerticalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLoginLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnvnamn)
                    .addComponent(tfAnvnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLosen)
                    .addComponent(tfLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLoggain)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pStartsidaLayout = new javax.swing.GroupLayout(pStartsida);
        pStartsida.setLayout(pStartsidaLayout);
        pStartsidaLayout.setHorizontalGroup(
            pStartsidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pStartsidaLayout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(lblVitslogga)
                .addGap(36, 36, 36)
                .addComponent(pLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        pStartsidaLayout.setVerticalGroup(
            pStartsidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pStartsidaLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(pStartsidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pStartsidaLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(pLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblVitslogga))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        tpMeny.addTab("Startsida", pStartsida);

        pReseforskott.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pReseforskottLayout = new javax.swing.GroupLayout(pReseforskott);
        pReseforskott.setLayout(pReseforskottLayout);
        pReseforskottLayout.setHorizontalGroup(
            pReseforskottLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );
        pReseforskottLayout.setVerticalGroup(
            pReseforskottLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        tpMeny.addTab("Reseförskott", pReseforskott);

        pReseutlägg.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pReseutläggLayout = new javax.swing.GroupLayout(pReseutlägg);
        pReseutlägg.setLayout(pReseutläggLayout);
        pReseutläggLayout.setHorizontalGroup(
            pReseutläggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        pReseutläggLayout.setVerticalGroup(
            pReseutläggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        tpMeny.addTab("Reseutlägg", pReseutlägg);

        pRapporter.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pRapporterLayout = new javax.swing.GroupLayout(pRapporter);
        pRapporter.setLayout(pRapporterLayout);
        pRapporterLayout.setHorizontalGroup(
            pRapporterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        pRapporterLayout.setVerticalGroup(
            pRapporterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        tpMeny.addTab("Rapporter", pRapporter);

        pAdmin.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pAdminLayout = new javax.swing.GroupLayout(pAdmin);
        pAdmin.setLayout(pAdminLayout);
        pAdminLayout.setHorizontalGroup(
            pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        pAdminLayout.setVerticalGroup(
            pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        tpMeny.addTab("Admin", pAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpMeny, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpMeny)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Meny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoggain;
    private javax.swing.JLabel lblAnvnamn;
    private javax.swing.JLabel lblLosen;
    private javax.swing.JLabel lblVitslogga;
    private javax.swing.JPanel pAdmin;
    private javax.swing.JPanel pLogin;
    private javax.swing.JPanel pRapporter;
    private javax.swing.JPanel pReseforskott;
    private javax.swing.JPanel pReseutlägg;
    private javax.swing.JPanel pStartsida;
    private javax.swing.JTextField tfAnvnamn;
    private javax.swing.JTextField tfLosen;
    private javax.swing.JTabbedPane tpMeny;
    // End of variables declaration//GEN-END:variables
}
